// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260129191640_AddProiectSantierEchipaAngajatLucrare")]
    partial class AddProiectSantierEchipaAngajatLucrare
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Entities.Angajat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Competente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EchipaId")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EchipaId");

                    b.ToTable("Angajati");
                });

            modelBuilder.Entity("Backend.Entities.Echipa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SefEchipaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SefEchipaId");

                    b.ToTable("Echipe");
                });

            modelBuilder.Entity("Backend.Entities.Lucrare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descriere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EchipaId")
                        .HasColumnType("int");

                    b.Property<int>("SantierId")
                        .HasColumnType("int");

                    b.Property<string>("Stare")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Termen")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EchipaId");

                    b.HasIndex("SantierId");

                    b.ToTable("Lucrari");
                });

            modelBuilder.Entity("Backend.Entities.Proiect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataSfarsit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stare")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Proiecte");
                });

            modelBuilder.Entity("Backend.Entities.Santier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descriere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProiectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProiectId");

                    b.ToTable("Santier");
                });

            modelBuilder.Entity("Backend.Entities.Utilizator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ParolaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilizatori");
                });

            modelBuilder.Entity("Backend.Entities.Angajat", b =>
                {
                    b.HasOne("Backend.Entities.Echipa", "Echipa")
                        .WithMany("Angajati")
                        .HasForeignKey("EchipaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Echipa");
                });

            modelBuilder.Entity("Backend.Entities.Echipa", b =>
                {
                    b.HasOne("Backend.Entities.Angajat", "SefEchipa")
                        .WithMany()
                        .HasForeignKey("SefEchipaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SefEchipa");
                });

            modelBuilder.Entity("Backend.Entities.Lucrare", b =>
                {
                    b.HasOne("Backend.Entities.Echipa", "Echipa")
                        .WithMany("Lucrari")
                        .HasForeignKey("EchipaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Entities.Santier", "Santier")
                        .WithMany("Lucrari")
                        .HasForeignKey("SantierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Echipa");

                    b.Navigation("Santier");
                });

            modelBuilder.Entity("Backend.Entities.Santier", b =>
                {
                    b.HasOne("Backend.Entities.Proiect", "Proiect")
                        .WithMany("Santier")
                        .HasForeignKey("ProiectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proiect");
                });

            modelBuilder.Entity("Backend.Entities.Echipa", b =>
                {
                    b.Navigation("Angajati");

                    b.Navigation("Lucrari");
                });

            modelBuilder.Entity("Backend.Entities.Proiect", b =>
                {
                    b.Navigation("Santier");
                });

            modelBuilder.Entity("Backend.Entities.Santier", b =>
                {
                    b.Navigation("Lucrari");
                });
#pragma warning restore 612, 618
        }
    }
}
