// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Entities.Angajat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Competente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EchipaId")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EchipaId");

                    b.ToTable("Angajati");
                });

            modelBuilder.Entity("Backend.Entities.Echipa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SefEchipaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SefEchipaId");

                    b.ToTable("Echipe");
                });

            modelBuilder.Entity("Backend.Entities.Lucrare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descriere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SantierId")
                        .HasColumnType("int");

                    b.Property<string>("Stare")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Termen")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SantierId");

                    b.ToTable("Lucrari");
                });

            modelBuilder.Entity("Backend.Entities.Proiect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Buget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataSfarsit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stare")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Moneda")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Proiecte");
                });

            modelBuilder.Entity("Backend.Entities.ProiectComentariu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCreare")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProiectId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("UtilizatorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProiectId");

                    b.HasIndex("UtilizatorId");

                    b.ToTable("ProiectComentarii");
                });

            modelBuilder.Entity("Backend.Entities.ProiectFisier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Continut")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("DataIncarcare")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeOriginal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProiectId")
                        .HasColumnType("int");

                    b.Property<string>("TipFisier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UtilizatorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProiectId");

                    b.HasIndex("UtilizatorId");

                    b.ToTable("ProiectFisiere");
                });

            modelBuilder.Entity("Backend.Entities.Santier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descriere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProiectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProiectId");

                    b.ToTable("Santier");
                });

            modelBuilder.Entity("Backend.Entities.Utilizator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AngajatId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ParolaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AngajatId")
                        .IsUnique()
                        .HasFilter("[AngajatId] IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilizatori");
                });

            modelBuilder.Entity("EchipaLucrare", b =>
                {
                    b.Property<int>("EchipeId")
                        .HasColumnType("int");

                    b.Property<int>("LucrariId")
                        .HasColumnType("int");

                    b.HasKey("EchipeId", "LucrariId");

                    b.HasIndex("LucrariId");

                    b.ToTable("LucrareEchipa", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.Angajat", b =>
                {
                    b.HasOne("Backend.Entities.Echipa", "Echipa")
                        .WithMany("Angajati")
                        .HasForeignKey("EchipaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Echipa");
                });

            modelBuilder.Entity("Backend.Entities.Echipa", b =>
                {
                    b.HasOne("Backend.Entities.Angajat", "SefEchipa")
                        .WithMany()
                        .HasForeignKey("SefEchipaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SefEchipa");
                });

            modelBuilder.Entity("Backend.Entities.Lucrare", b =>
                {
                    b.HasOne("Backend.Entities.Santier", "Santier")
                        .WithMany("Lucrari")
                        .HasForeignKey("SantierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Santier");
                });

            modelBuilder.Entity("Backend.Entities.ProiectComentariu", b =>
                {
                    b.HasOne("Backend.Entities.Proiect", "Proiect")
                        .WithMany("Comentarii")
                        .HasForeignKey("ProiectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Entities.Utilizator", "Utilizator")
                        .WithMany()
                        .HasForeignKey("UtilizatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proiect");

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("Backend.Entities.ProiectFisier", b =>
                {
                    b.HasOne("Backend.Entities.Proiect", "Proiect")
                        .WithMany("Fisiere")
                        .HasForeignKey("ProiectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Entities.Utilizator", "Utilizator")
                        .WithMany()
                        .HasForeignKey("UtilizatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proiect");

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("Backend.Entities.Santier", b =>
                {
                    b.HasOne("Backend.Entities.Proiect", "Proiect")
                        .WithMany("Santier")
                        .HasForeignKey("ProiectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proiect");
                });

            modelBuilder.Entity("Backend.Entities.Utilizator", b =>
                {
                    b.HasOne("Backend.Entities.Angajat", "Angajat")
                        .WithOne("Utilizator")
                        .HasForeignKey("Backend.Entities.Utilizator", "AngajatId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Angajat");
                });

            modelBuilder.Entity("EchipaLucrare", b =>
                {
                    b.HasOne("Backend.Entities.Echipa", null)
                        .WithMany()
                        .HasForeignKey("EchipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Entities.Lucrare", null)
                        .WithMany()
                        .HasForeignKey("LucrariId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Entities.Angajat", b =>
                {
                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("Backend.Entities.Echipa", b =>
                {
                    b.Navigation("Angajati");
                });

            modelBuilder.Entity("Backend.Entities.Proiect", b =>
                {
                    b.Navigation("Comentarii");

                    b.Navigation("Fisiere");

                    b.Navigation("Santier");
                });

            modelBuilder.Entity("Backend.Entities.Santier", b =>
                {
                    b.Navigation("Lucrari");
                });
#pragma warning restore 612, 618
        }
    }
}
